name = "SaccharumAppDemo.jl"
uuid = "5c5d0f80-0000-0000-0000-000000000000"
version = "0.1.0"
authors = ["Research Fellow"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieSession = "03cc5b98-4f21-4eb6-99f2-22eced81f962"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
Genie = "5.35.6"
GenieSession = "1.1.2"
HTTP = "1.10.19"
JSON = "1.4.0"
Logging = "1.11.0"
MbedTLS = "1.1.9"
SQLite = "1.8.0"
SearchLight = "2.11.2"
SearchLightSQLite = "2.2.2"
