name = "SaccharumAppDemo.jl"
uuid = "5c5d0f80-0000-0000-0000-000000000000"
version = "0.1.0"
authors = ["Research Fellow"]

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieAuthentication = "e115e502-7e3a-11e9-29b2-aba8be6c6778"
GenieSession = "03cc5b98-4f21-4eb6-99f2-22eced81f962"
GenieSessionFileSession = "5c4fdc26-39e3-47cf-9034-e533e09961c2"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Genie = "5.35.6"
GenieAuthentication = "2.2.0"
GenieSession = "1.1.2"
GenieSessionFileSession = "1.1.0"
SearchLight = "2.11.2"
SearchLightSQLite = "2.2.2"
Test = "1.11.0"
